# Generated by Django 3.0.3 on 2022-06-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20220630_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userFirsName',
            new_name='userFirstName',
        ),
    ]
