# Generated by Django 3.0.3 on 2022-06-30 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesMaster',
            fields=[
                ('categoryId', models.AutoField(db_column='category_id', db_index=True, primary_key=True, serialize=False)),
                ('catName', models.CharField(db_column='cat_name', max_length=255)),
                ('status', models.CharField(db_column='status', default='A', max_length=1)),
            ],
            options={
                'db_table': 'categories_master',
            },
        ),
        migrations.CreateModel(
            name='ItemsTable',
            fields=[
                ('itemId', models.AutoField(db_column='product_id', db_index=True, primary_key=True, serialize=False)),
                ('brandName', models.CharField(db_column='brand_name', max_length=255, null=True)),
                ('description', models.TextField(db_column='description', null=True)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
                ('rating', models.FloatField(db_column='save_rating', default=0)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='updated_at')),
                ('created_by', models.IntegerField(db_column='created_by')),
                ('updated_by', models.DateTimeField(db_column='updated_by')),
                ('status', models.CharField(db_column='status', default='A', max_length=1)),
                ('categoryId', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='Items.CategoriesMaster')),
            ],
            options={
                'db_table': 'item_table',
            },
        ),
    ]
