# Generated by Django 3.0.3 on 2022-07-04 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Items', '0002_auto_20220701_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingTable',
            fields=[
                ('Id', models.AutoField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('userName', models.CharField(db_column='user_name', max_length=255, null=True)),
                ('rating', models.FloatField(db_column='save_rating', default=0)),
                ('review', models.TextField(db_column='review')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_column='updated_at')),
                ('itemId', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='Items.ItemsTable')),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating_table',
            },
        ),
    ]
