# Generated by Django 3.0.3 on 2022-07-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_auto_20220704_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstable',
            name='itemId',
            field=models.AutoField(db_column='item_id', db_index=True, primary_key=True, serialize=False),
        ),
    ]
