# Generated by Django 3.0.3 on 2022-07-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_auto_20220704_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstable',
            name='itemId',
            field=models.AutoField(db_column='item_id', primary_key=True, serialize=False),
        ),
    ]
