# Generated by Django 3.0.3 on 2022-07-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0006_auto_20220704_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstable',
            name='userCount',
            field=models.IntegerField(db_column='user_count', default=1),
            preserve_default=False,
        ),
    ]
