# Generated by Django 3.0.3 on 2022-06-30 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('invoiceId', models.IntegerField(db_column='invoice_id')),
                ('discountId', models.IntegerField(db_column='discount_id')),
                ('amount', models.IntegerField(db_column='amount')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('itemId', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='Items.ItemsTable')),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cartItemId', models.AutoField(db_column='cart_item_id', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('price', models.IntegerField(db_column='price')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('createBy', models.IntegerField(db_column='create_by')),
                ('modifyBy', models.IntegerField(db_column='modify_by')),
                ('itemId', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='Items.ItemsTable')),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart_item',
            },
        ),
    ]
